### ISSUE TITLE
Remove unneeded CSS that AMP isn't stripping out

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1549]
When working on a recent site with a lot of Custom CSS, I noticed there are a number of things not getting stripped out by AMP, even though they're not used. This is because they include things like `@keyframes`, `@font-face`, or CSS Variables. 

Specifically on this site, this list included: 

- [x]  mediaelement-css~~ - (304b) - to be removed in #1548.
- [x]  wc-blocks-vendors-style-css (198b) - optionally removed from home in #1555
- [x]  wc-blocks-style-css (1973b) - optionally removed from home in #1555
- [ ]  newspack-listings-styles-css (460b)
- [x]  woocommerce-layout-css (285b) - optionally removed from home in #1555
- [x]  woocommerce-smallscreen-css (328b) - optionally removed from home in #1555
- [x]  newspack-woocommerce-style-css (1381b) - to be simplified in #1550, and optionally removed from homepage in #1559
- [ ]  social-logos-css (921b) - Jetpack (widget not used on site)

Other sites have included 
- [ ] CSS from Gravity Forms (amount TK)

Total from this site: 4607b, or a little over 6% of the allowed CSS -- it's not a ton, but it adds up when the site also has a lot! 

I imagine this varies from site to site, depending on what plugins they have installed.

This is a known issue in the [AMP plugin repo](https://github.com/ampproject/amp-wp/issues/4095),  but I think we might be able to do some things in the theme that could help for the short term -- things like disabling WooCommerce styles in all but the WooCommerce pages, and optionally turning off the WC block styles if a site isn't using them (especially on the homepage). We may also be able to check if the Jetpack Social Links widget is in use before enqueuing those styles.

**Comment by laurelfulford** [comment]
Closing this task for now; the AMP plugin is now allowing CSS overages, and for most sites, the problematic CSS varies, and is coming from different plugins.
