### ISSUE TITLE
Build theme header

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#96]
The Newspack theme's header is kind of complex, so I wanted to list out the requirements in an issue so I can keep track of it. The tasks listed here will likely grow longer, and may at some point be broken out into separate issues where it makes sense.

- [x] Build base styles for desktop
- [x] Build base styles for AMP (mobile and desktop) - started in #120
- [x] Build non-AMP styles and behaviour for mobile menu
- [ ] Make sure non-mobile menu works well on touch devices - AMP
- [ ] Make sure non-mobile menu works well on touch devices - non-AMP
- [x] Add 'header background' toggle and add styles
- [x] Add 'logo center' toggle and add styles (related exploration #72)
- [x] Add 'shorter' toggle and add styles (related exploration #72) - PR pending in #119
- [ ] ~~Add 'overlap' toggle and add styles (related exploration #72)~~ have opted to move this to the style pack -- see discussion in #112 
- [ ] Add 'overflow' offscreen menu, both for sections and for menus not shown in some cases (like the 'shorter' simplified menu). 
- [x] Add search icon and ability to toggle the search - PR pending in #116
- [x] Test/fix/add custom colour support
- [x] Test/fix/add custom typography support

Some related issues:

Needs Design: #89, #85 

Enhancements: #90, #88, #84

**Comment by laurelfulford** [comment]
Though the exact tasks aren't completed as written, I would consider the theme header complete; we can handle specific requests in different issues as they come up.
